/**
 * Static product catalog from MU Enterprises & Medisol Enterprises.
 * Used as the primary data source for /products when Sanity CMS is not configured.
 */

export type CatalogCategory =
  | 'Herbal Extracts'
  | 'Ayurvedic Botanicals'
  | 'Amino Acids'
  | 'Essential Oils'
  | 'Pharmaceutical Excipients'
  | 'Pharmaceutical APIs'
  | 'Flavours & Fragrances'
  | 'Nutraceuticals';

export interface CatalogProduct {
  id: string;
  name: string;
  botanicalName?: string;
  category: CatalogCategory;
  chemicalMarker?: string;
  standardization?: string;
  uses: string[];
  benefits: string[];
  applications?: string[];
  shortDescription: string;
  moq?: string;
  slug: string;
  featured?: boolean;
  img?: string;
}

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // ─── HERBAL EXTRACTS & AYURVEDIC BOTANICALS ────────────────────────────────
  {
    id: 'ashwagandha',
    name: 'Ashwagandha Extract',
    botanicalName: 'Withania somnifera',
    category: 'Herbal Extracts',
    chemicalMarker: 'Withanolides',
    standardization: 'Withanolides 2.5–10% by HPLC',
    uses: ['Adaptogen', 'Immunomodulator', 'Antioxidant'],
    benefits: ['Stress & anxiety relief', 'Hormonal balance', 'Energy & stamina', 'Cognitive support'],
    applications: ['Nutraceuticals', 'Sports nutrition', 'Ayurvedic formulations', 'Wellness supplements'],
    shortDescription: 'India\'s premier adaptogen root extract. Clinically validated to lower cortisol, support testosterone, and enhance endurance. Available as standardised root extract and KSM-66 equivalent.',
    moq: '25 kg',
    slug: 'ashwagandha-extract',
    featured: true,
    img: 'https://images.pexels.com/photos/10902685/pexels-photo-10902685.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'turmeric-curcumin',
    name: 'Turmeric Curcumin Extract',
    botanicalName: 'Curcuma longa',
    category: 'Herbal Extracts',
    chemicalMarker: 'Curcuminoids',
    standardization: 'Curcuminoids 95% by HPLC',
    uses: ['Anti-inflammatory', 'Antioxidant', 'Carminative', 'Stomachic'],
    benefits: ['Joint & bone health', 'Liver protection', 'Anti-inflammatory', 'Gut health'],
    applications: ['Nutraceuticals', 'Functional foods', 'Cosmetics', 'Pharma tablets'],
    shortDescription: 'Golden standard of Ayurvedic anti-inflammatories. Pharmaceutical-grade curcuminoid extract with 95% purity for joint health, liver support, and metabolic formulations.',
    moq: '25 kg',
    slug: 'turmeric-curcumin-extract',
    featured: true,
    img: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600&h=400&fit=crop&q=80',
  },
  {
    id: 'boswellia-serrata',
    name: 'Boswellia Serrata Extract',
    botanicalName: 'Boswellia serrata',
    category: 'Herbal Extracts',
    chemicalMarker: 'Boswellic Acids',
    standardization: 'Boswellic acids 65–85% by HPLC; AKBA ≥ 10%',
    uses: ['Anti-inflammatory', 'Antiarthritic', 'Analgesic'],
    benefits: ['Joint flexibility', 'Osteoarthritis relief', 'Anti-inflammatory', 'Respiratory support'],
    applications: ['Orthopaedic supplements', 'Sports nutrition', 'Pain management formulas'],
    shortDescription: 'High-potency resin extract standardised for boswellic acids including AKBA — the most clinically researched anti-inflammatory compound for joint health and mobility.',
    moq: '25 kg',
    slug: 'boswellia-serrata-extract',
    featured: true,
    img: 'https://images.pexels.com/photos/6693655/pexels-photo-6693655.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'gymnema-sylvestre',
    name: 'Gymnema Sylvestre Extract',
    botanicalName: 'Gymnema sylvestre',
    category: 'Herbal Extracts',
    chemicalMarker: 'Gymnemic acids',
    standardization: 'Gymnemic acids 25–75% by gravimetry',
    uses: ['Anti-diabetic', 'Diuretic', 'Blood sugar regulation'],
    benefits: ['Blood glucose control', 'Sugar craving reduction', 'Pancreatic support', 'Weight management'],
    applications: ['Diabetes supplements', 'Weight management', 'Metabolic health formulas'],
    shortDescription: 'The "sugar destroyer" — leaf extract that suppresses sweet taste receptors and supports healthy blood glucose levels. Widely used in anti-diabetic nutraceutical formulations globally.',
    moq: '25 kg',
    slug: 'gymnema-sylvestre-extract',
    img: 'https://images.pexels.com/photos/7474362/pexels-photo-7474362.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'garcinia-cambogia',
    name: 'Garcinia Cambogia Extract',
    botanicalName: 'Garcinia cambogia',
    category: 'Herbal Extracts',
    chemicalMarker: 'HCA (Hydroxycitric Acid)',
    standardization: 'HCA 50–60% by titration',
    uses: ['Anti-obesity', 'Lipid management', 'Appetite suppressant'],
    benefits: ['Weight management', 'Fat metabolism', 'Appetite control', 'Cholesterol support'],
    applications: ['Weight loss supplements', 'Metabolic formulas', 'Sports nutrition'],
    shortDescription: 'Tropical fruit rind extract rich in Hydroxycitric Acid — one of the most popular weight management ingredients globally, inhibiting fat synthesis and reducing appetite.',
    moq: '25 kg',
    slug: 'garcinia-cambogia-extract',
    img: 'https://images.pexels.com/photos/5938/food-salad-healthy-nature.jpg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'coleus-forskohlii',
    name: 'Coleus Forskohlii Extract',
    botanicalName: 'Coleus forskohlii',
    category: 'Herbal Extracts',
    chemicalMarker: 'Forskolin',
    standardization: 'Forskolin 10–20% by HPLC',
    uses: ['Camp stimulator', 'Hypotensive', 'Weight management'],
    benefits: ['Fat burning (cAMP activation)', 'Cardiovascular support', 'Testosterone support', 'Thyroid health'],
    applications: ['Weight loss supplements', 'Sports nutrition', 'Cardiovascular formulas'],
    shortDescription: 'Root extract standardised for forskolin — a unique diterpene that activates adenylyl cyclase to raise cAMP levels, supporting fat metabolism, cardiovascular function, and hormonal health.',
    moq: '25 kg',
    slug: 'coleus-forskohlii-extract',
    img: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=400&fit=crop&q=80',
  },
  {
    id: 'andrographis-kalmegh',
    name: 'Andrographis / Kalmegh Extract',
    botanicalName: 'Andrographis paniculata',
    category: 'Herbal Extracts',
    chemicalMarker: 'Andrographolides',
    standardization: 'Andrographolides 10–50% by HPLC',
    uses: ['Hepatoprotectant', 'Anti-viral', 'Immunomodulator'],
    benefits: ['Liver protection', 'Immune enhancement', 'Anti-viral activity', 'Fever reduction'],
    applications: ['Liver health supplements', 'Immune formulas', 'Ayurvedic tablets'],
    shortDescription: 'Bitter herb extract with potent andrographolide content — clinically studied for liver protection, immune activation, and antiviral properties. Widely used in hepatoprotective formulations.',
    moq: '25 kg',
    slug: 'andrographis-kalmegh-extract',
    img: 'https://images.pexels.com/photos/7108367/pexels-photo-7108367.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'amla',
    name: 'Amla Extract',
    botanicalName: 'Emblica officinalis',
    category: 'Herbal Extracts',
    chemicalMarker: 'Tannins, Vitamin C',
    standardization: 'Tannins 40–80%; Vitamin C ≥ 25%',
    uses: ['Anti-oxidant', 'Tonic', 'Immunomodulator'],
    benefits: ['Potent antioxidant', 'Collagen synthesis', 'Immunity boost', 'Digestive tonic'],
    applications: ['Vitamin C supplements', 'Hair & skin care', 'Anti-aging formulas', 'Ayurvedic tonics'],
    shortDescription: 'Indian gooseberry — one of nature\'s richest sources of bioavailable Vitamin C and polyphenols. Cold-processed fruit extract for immune, skin, hair, and anti-aging formulations.',
    moq: '25 kg',
    slug: 'amla-extract',
    featured: true,
    img: 'https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'giloy-guduchi',
    name: 'Giloy / Guduchi Extract',
    botanicalName: 'Tinospora cordifolia',
    category: 'Herbal Extracts',
    chemicalMarker: 'Tinosporin, Bitters',
    standardization: 'Bitters 2.5–5%',
    uses: ['Immunomodulator', 'Anti-diabetic', 'Febrifuge', 'Antioxidant'],
    benefits: ['Immunity enhancement', 'Blood sugar regulation', 'Anti-inflammatory', 'Liver detox'],
    applications: ['Immune supplements', 'Adaptogen blends', 'Diabetic formulas', 'Ayurvedic classics'],
    shortDescription: 'The Ayurvedic "divine nectar" — stem extract rich in tinosporin and bitter glycosides with well-documented immunomodulatory, anti-inflammatory, and hepatoprotective activity.',
    moq: '25 kg',
    slug: 'giloy-guduchi-extract',
    img: 'https://images.pexels.com/photos/5945559/pexels-photo-5945559.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'shatavari',
    name: 'Shatavari Extract',
    botanicalName: 'Asparagus racemosus',
    category: 'Herbal Extracts',
    chemicalMarker: 'Saponins, Shatavarin',
    standardization: 'Saponins 20–40% by gravimetry',
    uses: ['Galactagogue', 'Aphrodisiac', 'Adaptogen'],
    benefits: ['Female hormonal balance', 'Lactation support', 'Reproductive health', 'Adaptogenic'],
    applications: ['Women\'s health supplements', 'Lactation formulas', 'Hormone support', 'Ayurvedic tonics'],
    shortDescription: 'Premier Ayurvedic tonic for women\'s health. Root extract standardised for shatavarin saponins — clinically used for hormonal balance, lactation enhancement, and reproductive wellness.',
    moq: '25 kg',
    slug: 'shatavari-extract',
    img: 'https://images.pexels.com/photos/2317711/pexels-photo-2317711.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'brahmi-centella',
    name: 'Brahmi / Centella Asiatica Extract',
    botanicalName: 'Centella asiatica',
    category: 'Herbal Extracts',
    chemicalMarker: 'Asiaticosides, Asiatic acid',
    standardization: 'Total triterpenoids 40% by HPLC',
    uses: ['Memory enhancer', 'Neuroprotective', 'Wound healing', 'Leprostatic'],
    benefits: ['Cognitive enhancement', 'Memory & focus', 'Skin repair', 'Stress reduction'],
    applications: ['Nootropic supplements', 'Skin care cosmetics', 'Brain health formulas'],
    shortDescription: 'Dual-action extract from the classic brain herb — delivering asiaticoside-rich powder for cognitive enhancement and wound healing applications in nutraceuticals and cosmeceuticals.',
    moq: '25 kg',
    slug: 'brahmi-centella-extract',
    img: 'https://images.pexels.com/photos/6157052/pexels-photo-6157052.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'gokhru-tribulus',
    name: 'Gokhru / Tribulus Extract',
    botanicalName: 'Tribulus terrestris',
    category: 'Herbal Extracts',
    chemicalMarker: 'Saponins (Protodioscin)',
    standardization: 'Saponins 40–90% by gravimetry',
    uses: ['Spermatogenic', 'Ovagenic', 'Stimulator'],
    benefits: ['Testosterone support', 'Male fertility', 'Athletic performance', 'Libido enhancement'],
    applications: ['Sports nutrition', 'Men\'s health supplements', 'Fertility formulas'],
    shortDescription: 'Potent fruit extract standardised for steroidal saponins including protodioscin — the most researched ingredient for testosterone support, male fertility, and athletic performance globally.',
    moq: '25 kg',
    slug: 'gokhru-tribulus-extract',
    img: 'https://images.pexels.com/photos/4021983/pexels-photo-4021983.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'hibiscus',
    name: 'Hibiscus Extract',
    botanicalName: 'Hibiscus rosa sinensis',
    category: 'Herbal Extracts',
    chemicalMarker: 'Anthroquinones, Flavonoids',
    standardization: 'Anthocyanins ≥ 5%',
    uses: ['Poultice', 'Rich in iron', 'Cardiovascular support'],
    benefits: ['Blood pressure support', 'Rich in antioxidants', 'Liver health', 'Weight management'],
    applications: ['Cardiovascular supplements', 'Hair care', 'Functional beverages', 'Antioxidant blends'],
    shortDescription: 'Vibrant flower extract packed with anthocyanins and flavonoids — widely used for blood pressure management, antioxidant support, and natural red-pink colouring in functional food applications.',
    moq: '25 kg',
    slug: 'hibiscus-extract',
    img: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'green-coffee',
    name: 'Green Coffee Extract',
    botanicalName: 'Coffea arabica / robusta',
    category: 'Herbal Extracts',
    chemicalMarker: 'Chlorogenic Acid',
    standardization: 'Chlorogenic acids 45–50% by HPLC',
    uses: ['Weight management', 'Blood sugar regulation', 'Antioxidant'],
    benefits: ['Fat oxidation', 'Blood glucose control', 'Antioxidant', 'Energy boost'],
    applications: ['Weight management supplements', 'Metabolic health', 'Sports nutrition'],
    shortDescription: 'Unroasted coffee bean extract retaining high chlorogenic acid content — one of the most researched weight management ingredients, supporting fat metabolism and blood glucose regulation.',
    moq: '25 kg',
    slug: 'green-coffee-extract',
    img: 'https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'green-tea',
    name: 'Green Tea Extract',
    botanicalName: 'Camellia sinensis',
    category: 'Herbal Extracts',
    chemicalMarker: 'EGCG, Polyphenols',
    standardization: 'EGCG 50–98% by HPLC',
    uses: ['Antioxidant', 'Weight management', 'Cognitive clarity'],
    benefits: ['Potent antioxidant', 'Metabolism boost', 'Cognitive support', 'Cardioprotective'],
    applications: ['Weight loss supplements', 'Nootropics', 'Anti-aging formulas', 'Functional beverages'],
    shortDescription: 'One of the most researched antioxidants globally — EGCG-rich leaf extract for weight management, cognitive enhancement, cardioprotection, and premium anti-aging formulations.',
    moq: '25 kg',
    slug: 'green-tea-extract',
    img: 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=600&h=400&fit=crop&q=80',
  },
  {
    id: 'neem',
    name: 'Neem Extract',
    botanicalName: 'Azadirachta indica',
    category: 'Herbal Extracts',
    chemicalMarker: 'Azadirachtin',
    standardization: 'Azadirachtin 0.3–3%',
    uses: ['Anti-bacterial', 'Skin & hair care', 'Immunomodulator'],
    benefits: ['Skin purification', 'Anti-bacterial', 'Hair health', 'Immune support'],
    applications: ['Derma formulations', 'Oral care', 'Hair care products', 'Immunity supplements'],
    shortDescription: 'Nature\'s purifier — leaf & bark extract standardised for azadirachtin with broad-spectrum antibacterial activity for derma, hair care, oral hygiene, and immune support formulations.',
    moq: '25 kg',
    slug: 'neem-extract',
    img: 'https://images.pexels.com/photos/16061011/pexels-photo-16061011.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'moringa',
    name: 'Moringa Extract',
    botanicalName: 'Moringa oleifera',
    category: 'Herbal Extracts',
    chemicalMarker: 'Total phenols, Morindin',
    standardization: 'Total phenols ≥ 5%',
    uses: ['Stimulant', 'Nutritional', 'Anti-inflammatory'],
    benefits: ['Rich in vitamins & minerals', 'Antioxidant', 'Energy & vitality', 'Nutritional fortification'],
    applications: ['Superfoods', 'Nutritional supplements', 'Protein powders', 'Functional foods'],
    shortDescription: 'The "miracle tree" leaf extract — naturally dense in vitamins A, C, E, iron, and calcium. Ideal for nutritional fortification, greens blends, and wellness supplement formulations.',
    moq: '25 kg',
    slug: 'moringa-extract',
    img: 'https://images.pexels.com/photos/33500190/pexels-photo-33500190.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'aloe-vera',
    name: 'Aloe Vera Extract',
    botanicalName: 'Aloe barbadensis miller',
    category: 'Herbal Extracts',
    chemicalMarker: 'Polysaccharides',
    standardization: 'Aloin ≤ 10 ppm; Polysaccharides ≥ 10%',
    uses: ['Skin hydration', 'Digestive health', 'Wound healing'],
    benefits: ['Skin hydration', 'Digestive support', 'Wound healing', 'Anti-aging'],
    applications: ['Cosmetics & skin care', 'Digestive supplements', 'Beverages', 'After-sun products'],
    shortDescription: 'Cold-processed gel extract preserving bioactive polysaccharides and enzymes. Available as clear juice, dry extract, and concentrated powder with verified aloin-free certification.',
    moq: '25 kg',
    slug: 'aloe-vera-extract',
    img: 'https://images.pexels.com/photos/7408838/pexels-photo-7408838.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'tulsi',
    name: 'Tulsi / Holy Basil Extract',
    botanicalName: 'Ocimum sanctum',
    category: 'Herbal Extracts',
    chemicalMarker: 'Tannins, Ursolic acid',
    standardization: 'Ursolic acid 2.5%; Essential oil ≥ 0.5%',
    uses: ['Adaptogen', 'Immunomodulator', 'Antibacterial'],
    benefits: ['Stress adaptation', 'Immunity boost', 'Respiratory support', 'Anti-bacterial'],
    applications: ['Adaptogen blends', 'Respiratory formulas', 'Immune supplements', 'Ayurvedic tonics'],
    shortDescription: 'Sacred herb of Ayurveda — ursolic acid-rich leaf extract with clinically documented adaptogenic, immunomodulatory, and antimicrobial properties for wellness and respiratory formulations.',
    moq: '25 kg',
    slug: 'tulsi-extract',
    img: 'https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'ginger',
    name: 'Ginger Dry Extract',
    botanicalName: 'Zingiber officinale',
    category: 'Herbal Extracts',
    chemicalMarker: 'Gingerols, Shogaols',
    standardization: 'Gingerols 5–10% by HPLC',
    uses: ['Anti-arthritic', 'Carminative', 'Antiemetic'],
    benefits: ['Nausea relief', 'Joint health', 'Digestive support', 'Anti-inflammatory'],
    applications: ['Digestive supplements', 'Joint health formulas', 'Sports nutrition', 'Functional foods'],
    shortDescription: 'Rhizome extract standardised for gingerols and shogaols — well-documented for nausea management, joint health, digestive comfort, and anti-inflammatory activity in nutraceutical formulas.',
    moq: '25 kg',
    slug: 'ginger-extract',
    img: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=400&fit=crop&q=80',
  },
  {
    id: 'guggul',
    name: 'Guggul Extract',
    botanicalName: 'Commiphora mukul',
    category: 'Herbal Extracts',
    chemicalMarker: 'Guggul Sterones (E&Z)',
    standardization: 'Guggulsterones E & Z ≥ 2.5–10%',
    uses: ['Antiarthritic', 'Antilipemic', 'Anticholesteremic'],
    benefits: ['Cholesterol management', 'Joint health', 'Anti-inflammatory', 'Thyroid support'],
    applications: ['Cardiovascular supplements', 'Cholesterol formulas', 'Weight management', 'Ortho formulas'],
    shortDescription: 'Resin extract from the mukul myrrh tree, standardised for guggulsterones E & Z — one of Ayurveda\'s most validated cholesterol-lowering and anti-arthritic ingredients.',
    moq: '25 kg',
    slug: 'guggul-extract',
    img: 'https://images.pexels.com/photos/4198712/pexels-photo-4198712.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'triphala',
    name: 'Triphala Extract',
    botanicalName: 'Terminalia chebula + T. belerica + Emblica officinalis',
    category: 'Herbal Extracts',
    chemicalMarker: 'Tannins',
    standardization: 'Tannins 25–45% by gravimetry',
    uses: ['Detoxificant', 'Laxative', 'Antioxidant'],
    benefits: ['Gut detox & cleansing', 'Digestive regularity', 'Antioxidant', 'Liver support'],
    applications: ['Detox supplements', 'Digestive health', 'Ayurvedic classics', 'Colon health'],
    shortDescription: 'Classic Ayurvedic tridoshic formula combining three myrobalan fruits — a complete digestive tonic, bowel regulator, and antioxidant powerhouse. Available as standardised polyphenol extract.',
    moq: '25 kg',
    slug: 'triphala-extract',
    img: 'https://images.pexels.com/photos/5765/nature-forest-moss-leaves.jpg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'shankhpushpi',
    name: 'Shankhpushpi Extract',
    botanicalName: 'Evolvulus alsinoides',
    category: 'Herbal Extracts',
    chemicalMarker: 'Bitters, Alkaloids',
    standardization: 'Bitters equivalent 2%',
    uses: ['Memory tonic', 'Nervine', 'Anxiolytic'],
    benefits: ['Memory & cognition', 'Stress & anxiety relief', 'Sleep quality', 'Nervous system support'],
    applications: ['Brain health supplements', 'Nootropic blends', 'Children\'s formulas', 'Stress management'],
    shortDescription: 'Traditional brain tonic herb — whole plant extract used in Ayurvedic medicine for centuries to enhance memory, reduce anxiety, and support healthy cognitive function.',
    moq: '25 kg',
    slug: 'shankhpushpi-extract',
    img: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'rosehip',
    name: 'Rosehip Dry Extract',
    botanicalName: 'Rosa canina',
    category: 'Herbal Extracts',
    chemicalMarker: 'Vitamin C, Bioflavonoids',
    standardization: 'Vitamin C ≥ 5%; Polyphenols ≥ 10%',
    uses: ['Antioxidant', 'Anti-inflammatory', 'Immune support'],
    benefits: ['Joint health', 'Skin collagen support', 'Immunity boost', 'Anti-inflammatory'],
    applications: ['Joint health formulas', 'Skin care supplements', 'Vitamin C blends', 'Anti-aging'],
    shortDescription: 'Vitamin C and bioflavonoid-rich fruit hip extract with documented anti-inflammatory activity for joint health, immune fortification, and skin collagen synthesis in premium supplements.',
    moq: '25 kg',
    slug: 'rosehip-extract',
    img: 'https://images.pexels.com/photos/1374294/pexels-photo-1374294.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'papaya',
    name: 'Papaya Leaf Extract',
    botanicalName: 'Carica papaya',
    category: 'Herbal Extracts',
    chemicalMarker: 'Papain, Carpaine',
    standardization: 'Papain activity ≥ 50,000 USP units/g',
    uses: ['Digestive enzyme', 'Platelet support', 'Anti-parasitic'],
    benefits: ['Digestive enzyme support', 'Platelet count enhancement', 'Immune support', 'Anti-oxidant'],
    applications: ['Digestive enzyme blends', 'Dengue support formulas', 'Immune supplements'],
    shortDescription: 'Proteolytic enzyme-rich leaf extract with documented activity for digestive support and platelet enhancement. Widely used in tropical disease support and digestive enzyme supplement formulations.',
    moq: '25 kg',
    slug: 'papaya-leaf-extract',
    img: 'https://images.pexels.com/photos/918643/pexels-photo-918643.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'devils-claw',
    name: "Devil's Claw Extract",
    botanicalName: 'Harpagophytum procumbens',
    category: 'Herbal Extracts',
    chemicalMarker: 'Harpagoside',
    standardization: 'Harpagoside 2–5% by HPLC',
    uses: ['Anti-inflammatory', 'Analgesic', 'Antiarthritic'],
    benefits: ['Joint pain relief', 'Anti-inflammatory', 'Muscle relaxation', 'Back pain support'],
    applications: ['Orthopaedic supplements', 'Pain management', 'Sports recovery formulas'],
    shortDescription: 'African root extract standardised for harpagoside — a clinically validated iridoid glycoside with significant anti-inflammatory and analgesic activity for joint, muscle, and back pain formulations.',
    moq: '25 kg',
    slug: 'devils-claw-extract',
    img: 'https://images.pexels.com/photos/2682927/pexels-photo-2682927.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'craneberry',
    name: 'Cranberry Extract',
    botanicalName: 'Vaccinium macrocarpon',
    category: 'Herbal Extracts',
    chemicalMarker: 'Proanthocyanidins (PAC)',
    standardization: 'PAC 36 mg (BL-DMAC method)',
    uses: ['Urinary tract health', 'Antioxidant', 'Anti-adhesion'],
    benefits: ['UTI prevention', 'Antioxidant', 'Urinary health', 'Anti-inflammatory'],
    applications: ['Urinary health supplements', 'Women\'s health', 'Antioxidant blends'],
    shortDescription: 'Proanthocyanidin-standardised berry extract with clinically demonstrated anti-adhesion activity against UTI-causing bacteria — the globally preferred ingredient for urinary tract health supplements.',
    moq: '25 kg',
    slug: 'cranberry-extract',
    img: 'https://images.pexels.com/photos/4021983/pexels-photo-4021983.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'pine-bark',
    name: 'Pine Bark Extract',
    botanicalName: 'Pinus pinaster / maritima',
    category: 'Herbal Extracts',
    chemicalMarker: 'Proanthocyanidins (OPC)',
    standardization: 'OPC ≥ 95% by UV; Polyphenols ≥ 65%',
    uses: ['Antioxidant', 'Cardiovascular', 'Anti-aging'],
    benefits: ['Powerful antioxidant (20× Vit C)', 'Cardiovascular health', 'Skin elasticity', 'Anti-inflammatory'],
    applications: ['Anti-aging supplements', 'Cardiovascular health', 'Skin care nutraceuticals'],
    shortDescription: 'Maritime pine bark extract rich in oligomeric proanthocyanidins (OPC) — among the most potent plant antioxidants available, with documented cardiovascular, skin, and anti-inflammatory benefits.',
    moq: '25 kg',
    slug: 'pine-bark-extract',
    img: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&h=400&fit=crop&q=80',
  },
  {
    id: 'evening-primrose',
    name: 'Evening Primrose Extract',
    botanicalName: 'Oenothera biennis',
    category: 'Herbal Extracts',
    chemicalMarker: 'GLA (Gamma-Linolenic Acid)',
    standardization: 'GLA 8–10% in seed oil',
    uses: ['Hormonal support', 'Skin health', 'Anti-inflammatory'],
    benefits: ['Female hormone balance', 'Skin hydration & health', 'PMS relief', 'Anti-inflammatory'],
    applications: ['Women\'s health supplements', 'Skin care nutraceuticals', 'Hormone balance formulas'],
    shortDescription: 'Seed oil and dry extract rich in gamma-linolenic acid (GLA) — an omega-6 fatty acid essential for hormonal balance, skin barrier function, and inflammatory modulation in women\'s health formulas.',
    moq: '25 kg',
    slug: 'evening-primrose-extract',
    img: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'cucumber',
    name: 'Cucumber Extract',
    botanicalName: 'Cucumis sativus',
    category: 'Herbal Extracts',
    chemicalMarker: 'Silica, Cucurbitacins',
    standardization: 'Silica ≥ 5%',
    uses: ['Skin hydration', 'Cooling', 'Diuretic'],
    benefits: ['Skin soothing', 'Hydration', 'Antioxidant', 'Anti-inflammatory'],
    applications: ['Cosmetics', 'Skin care formulations', 'After-sun products', 'Toners'],
    shortDescription: 'Soothing vegetable extract with high silica and cucurbitacin content — widely used in cosmetic and nutraceutical formulations for skin hydration, cooling, and mild diuretic support.',
    moq: '25 kg',
    slug: 'cucumber-extract',
    img: 'https://images.pexels.com/photos/5945559/pexels-photo-5945559.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'safed-musli',
    name: 'Safed Musli Extract',
    botanicalName: 'Chlorophytum borivilianum',
    category: 'Herbal Extracts',
    chemicalMarker: 'Saponins',
    standardization: 'Saponins ≥ 20% by gravimetry',
    uses: ['Aphrodisiac', 'Tonic', 'Adaptogen'],
    benefits: ['Male vitality & libido', 'Testosterone support', 'Stamina', 'Anti-fatigue'],
    applications: ['Men\'s health supplements', 'Sports nutrition', 'Sexual wellness formulas'],
    shortDescription: 'Prized Indian aphrodisiac root extract standardised for steroidal saponins — a key ingredient in Ayurvedic vitality tonics, men\'s health supplements, and sports performance formulas.',
    moq: '25 kg',
    slug: 'safed-musli-extract',
    img: 'https://images.pexels.com/photos/4021983/pexels-photo-4021983.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'hadjod',
    name: 'Hadjod Extract',
    botanicalName: 'Cissus quadrangularis',
    category: 'Herbal Extracts',
    chemicalMarker: 'Ketosterones',
    standardization: 'Ketosterones 2.5–5% by HPLC',
    uses: ['Bone healing', 'Joint support', 'Anabolic'],
    benefits: ['Fracture healing', 'Bone density', 'Joint strength', 'Weight management'],
    applications: ['Bone health supplements', 'Sports nutrition', 'Joint care formulas', 'Orthopedic support'],
    shortDescription: 'Bone-healing herb extract with unique ketosterone profile — clinically studied for accelerating fracture repair, improving bone density, and as a natural anabolic for sports nutrition.',
    moq: '25 kg',
    slug: 'hadjod-extract',
    img: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },

  // ─── AMINO ACIDS ────────────────────────────────────────────────────────────
  {
    id: 'l-arginine',
    name: 'L-Arginine HCl / Base',
    category: 'Amino Acids',
    chemicalMarker: 'L-Arginine',
    standardization: 'Purity ≥ 99% by HPLC',
    uses: ['Cardiovascular support', 'Sports nutrition', 'Nitric oxide precursor'],
    benefits: ['Vasodilation & blood flow', 'Athletic performance', 'Erectile support', 'Wound healing'],
    applications: ['Pre-workout supplements', 'Cardiovascular health', 'Male health formulas'],
    shortDescription: 'Pharmaceutical-grade L-Arginine in both HCl salt and free base forms — the primary nitric oxide precursor used in cardiovascular, erectile, and sports performance supplement formulations.',
    moq: '25 kg',
    slug: 'l-arginine',
    img: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'l-carnitine',
    name: 'L-Carnitine L-Tartrate',
    category: 'Amino Acids',
    chemicalMarker: 'L-Carnitine',
    standardization: 'L-Carnitine ≥ 68% (as L-tartrate)',
    uses: ['Fat metabolism', 'Energy production', 'Sports performance'],
    benefits: ['Fat burning', 'Energy metabolism', 'Muscle recovery', 'Cardiovascular health'],
    applications: ['Sports & weight loss supplements', 'Energy formulas', 'Cardiovascular support'],
    shortDescription: 'Highly bioavailable L-tartrate salt form of L-Carnitine — the gold standard for sports nutrition formulations targeting fat metabolism, energy production, and muscular recovery.',
    moq: '25 kg',
    slug: 'l-carnitine-tartrate',
    img: 'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'l-glutamine',
    name: 'L-Glutamine',
    category: 'Amino Acids',
    chemicalMarker: 'L-Glutamine',
    standardization: 'Purity ≥ 99% by HPLC',
    uses: ['Gut health', 'Immune support', 'Muscle recovery'],
    benefits: ['Gut lining repair', 'Muscle recovery', 'Immune support', 'Anti-catabolism'],
    applications: ['Sports nutrition', 'Gut health formulas', 'Critical care', 'Immune supplements'],
    shortDescription: 'The most abundant amino acid in plasma — pharmaceutical-grade L-Glutamine for gut integrity, immune function, and muscle recovery in sports nutrition and clinical nutrition products.',
    moq: '25 kg',
    slug: 'l-glutamine',
    img: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'l-glutathione',
    name: 'L-Glutathione (Reduced)',
    category: 'Amino Acids',
    chemicalMarker: 'GSH',
    standardization: 'Reduced GSH ≥ 98% by HPLC',
    uses: ['Antioxidant', 'Skin brightening', 'Detoxification'],
    benefits: ['Master antioxidant', 'Skin whitening', 'Liver detox', 'Anti-aging'],
    applications: ['Skin whitening supplements', 'Anti-aging', 'Liver support', 'IV infusion'],
    shortDescription: 'The body\'s master antioxidant in reduced active form — USP-grade glutathione for skin brightening, liver detoxification, anti-aging, and premium immune-boosting formulations.',
    moq: '1 kg',
    slug: 'l-glutathione-reduced',
    img: 'https://images.pexels.com/photos/3683056/pexels-photo-3683056.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'l-tryptophan',
    name: 'L-Tryptophan',
    category: 'Amino Acids',
    chemicalMarker: 'L-Tryptophan',
    standardization: 'Purity ≥ 98.5% by HPLC',
    uses: ['Serotonin precursor', 'Sleep support', 'Mood enhancement'],
    benefits: ['Sleep quality', 'Mood regulation', 'Stress relief', 'Serotonin synthesis'],
    applications: ['Sleep supplements', 'Mood & stress formulas', 'Nootropics'],
    shortDescription: 'Essential amino acid and direct serotonin precursor — pharmaceutical-grade L-Tryptophan for sleep quality improvement, mood regulation, and stress management supplement formulations.',
    moq: '25 kg',
    slug: 'l-tryptophan',
    img: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'taurine',
    name: 'L-Taurine',
    category: 'Amino Acids',
    chemicalMarker: 'Taurine',
    standardization: 'Purity ≥ 99% by HPLC',
    uses: ['Cardiovascular', 'Energy', 'Neuroprotective'],
    benefits: ['Heart health', 'Energy metabolism', 'Eye health', 'Electrolyte balance'],
    applications: ['Energy drinks', 'Sports nutrition', 'Cardiovascular supplements', 'Eye health'],
    shortDescription: 'Non-proteinogenic amino acid with cardiovascular and neuroprotective activity — pharmaceutical-grade L-Taurine, a key ingredient in energy drinks, sports nutrition, and heart health formulations.',
    moq: '25 kg',
    slug: 'l-taurine',
    img: 'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'glucosamine',
    name: 'Glucosamine HCl / Sulphate',
    category: 'Amino Acids',
    chemicalMarker: 'Glucosamine',
    standardization: 'Purity ≥ 99% (HCl) / ≥ 98.5% (Sulphate)',
    uses: ['Joint health', 'Cartilage repair', 'Anti-inflammatory'],
    benefits: ['Joint pain relief', 'Cartilage regeneration', 'Osteoarthritis support', 'Mobility improvement'],
    applications: ['Joint health supplements', 'Orthopaedic formulas', 'Sports recovery'],
    shortDescription: 'Pharmaceutical-grade glucosamine in both HCl and potassium/sodium sulphate forms — the world\'s most widely used joint health ingredient with extensive clinical evidence for osteoarthritis.',
    moq: '25 kg',
    slug: 'glucosamine',
    img: 'https://images.pexels.com/photos/6693655/pexels-photo-6693655.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'coenzyme-q10',
    name: 'Coenzyme Q10 (CoQ10)',
    category: 'Nutraceuticals',
    chemicalMarker: 'Ubiquinone',
    standardization: 'Ubiquinone ≥ 98% by HPLC',
    uses: ['Cardiovascular health', 'Mitochondrial energy', 'Antioxidant'],
    benefits: ['Heart health', 'Cellular energy production', 'Antioxidant protection', 'Anti-aging'],
    applications: ['Cardiovascular supplements', 'Anti-aging', 'Energy formulas', 'Statin adjunct therapy'],
    shortDescription: 'Premium pharmaceutical-grade CoQ10 (Ubiquinone) — essential for mitochondrial ATP production. Widely used in cardiovascular health, anti-aging, statin adjunct, and cellular energy formulations.',
    moq: '1 kg',
    slug: 'coenzyme-q10',
    img: 'https://images.pexels.com/photos/3683056/pexels-photo-3683056.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'spirulina',
    name: 'Spirulina Extract / Powder',
    category: 'Nutraceuticals',
    chemicalMarker: 'Phycocyanin, Protein',
    standardization: 'Protein ≥ 60%; Phycocyanin ≥ 15%',
    uses: ['Nutritional supplement', 'Antioxidant', 'Immunomodulator'],
    benefits: ['High protein content', 'Antioxidant', 'Immune support', 'Iron-rich'],
    applications: ['Greens supplements', 'Protein powders', 'Detox blends', 'Superfood formulas'],
    shortDescription: 'Pharmaceutical-grade Spirulina — one of the world\'s most nutrient-dense superfoods with ≥60% complete protein, phycocyanin antioxidants, and a complete spectrum of vitamins and minerals.',
    moq: '25 kg',
    slug: 'spirulina',
    img: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'sodium-hyaluronate',
    name: 'Sodium Hyaluronate',
    category: 'Nutraceuticals',
    chemicalMarker: 'Hyaluronic Acid',
    standardization: 'MW: Low (50–100 kDa), Medium (500–1000 kDa), High (1500+ kDa)',
    uses: ['Joint health', 'Skin hydration', 'Eye care'],
    benefits: ['Joint lubrication', 'Skin plumping & hydration', 'Eye moisture', 'Wound healing'],
    applications: ['Joint supplements', 'Skin care nutraceuticals', 'Ophthalmic formulas', 'Cosmetics'],
    shortDescription: 'Pharmaceutical-grade sodium hyaluronate in multiple molecular weights — the body\'s premier moisture-binding molecule for joint lubrication, skin hydration, and ophthalmic formulations.',
    moq: '1 kg',
    slug: 'sodium-hyaluronate',
    img: 'https://images.pexels.com/photos/3683056/pexels-photo-3683056.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'zeaxanthin',
    name: 'Zeaxanthin',
    category: 'Nutraceuticals',
    chemicalMarker: 'Zeaxanthin',
    standardization: 'Zeaxanthin ≥ 5% by HPLC',
    uses: ['Eye health', 'Antioxidant', 'Anti-aging'],
    benefits: ['Macular degeneration protection', 'Blue light filtering', 'Eye health', 'Antioxidant'],
    applications: ['Eye health supplements', 'Anti-aging formulas', 'Vision support'],
    shortDescription: 'Carotenoid antioxidant concentrated in the macular pigment of the human eye — used in eye health formulations for protection against macular degeneration, blue light, and oxidative damage.',
    moq: '1 kg',
    slug: 'zeaxanthin',
    img: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'lycopene',
    name: 'Lycopene (Powder & Oil)',
    category: 'Nutraceuticals',
    chemicalMarker: 'Lycopene',
    standardization: 'Lycopene 6% / 10% by HPLC',
    uses: ['Antioxidant', 'Prostate health', 'Cardiovascular'],
    benefits: ['Prostate health', 'Cardiovascular protection', 'Anti-cancer antioxidant', 'Skin protection'],
    applications: ['Prostate health supplements', 'Antioxidant blends', 'Cardiovascular health', 'Skin care'],
    shortDescription: 'Tomato-derived carotenoid available in both 6% and 10% standardised powder and oil dispersions — widely used for prostate health, cardiovascular protection, and antioxidant supplementation.',
    moq: '1 kg',
    slug: 'lycopene',
    img: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },

  // ─── ESSENTIAL OILS ──────────────────────────────────────────────────────────
  {
    id: 'menthol',
    name: 'Menthol IP/BP/USP',
    botanicalName: 'Mentha arvensis',
    category: 'Essential Oils',
    chemicalMarker: 'L-Menthol',
    standardization: 'L-Menthol ≥ 99%; IP/BP/USP grade',
    uses: ['Cooling', 'Analgesic', 'Antibacterial'],
    benefits: ['Topical cooling & pain relief', 'Nasal decongestant', 'Oral freshening', 'Antibacterial'],
    applications: ['Oral care', 'Topical analgesics', 'Cold & flu formulas', 'Confectionery flavouring'],
    shortDescription: 'Natural or synthetic pharmaceutical-grade menthol crystals meeting IP/BP/USP monograph — the universal cooling agent for oral care, topical pain relief, inhalation, and flavouring applications.',
    moq: '25 kg',
    slug: 'menthol',
    img: 'https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'natural-basil-oil',
    name: 'Natural Basil Oil',
    botanicalName: 'Ocimum basilicum',
    category: 'Essential Oils',
    chemicalMarker: 'Linalool, Eugenol',
    standardization: 'Linalool ≥ 40%; Eugenol ≥ 5%',
    uses: ['Flavouring', 'Antimicrobial', 'Aromatherapy'],
    benefits: ['Antimicrobial', 'Anti-stress & relaxant', 'Flavouring', 'Anti-spasmodic'],
    applications: ['Flavour & fragrance', 'Aromatherapy', 'Oral care', 'Cosmetics'],
    shortDescription: 'Steam-distilled sweet basil essential oil with high linalool content — used in premium flavour & fragrance applications, aromatherapy, oral care, and natural antimicrobial formulations.',
    moq: '5 kg',
    slug: 'natural-basil-oil',
    img: 'https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'natural-mentha-oil',
    name: 'Natural Mentha Oil',
    botanicalName: 'Mentha spicata / arvensis',
    category: 'Essential Oils',
    chemicalMarker: 'Menthol, Menthone',
    standardization: 'Menthol 65–75%; Menthone 12–20%',
    uses: ['Flavouring', 'Cooling', 'Pharmaceutical'],
    benefits: ['Cooling & refreshing', 'Digestive comfort', 'Oral freshening', 'Inhalation therapy'],
    applications: ['Oral care & toothpaste', 'Pharma formulations', 'Confectionery', 'Beverage flavouring'],
    shortDescription: 'Natural peppermint and cornmint essential oils — high menthol content for pharmaceutical, oral care, flavour, and fragrance applications meeting international pharmacopoeia standards.',
    moq: '5 kg',
    slug: 'natural-mentha-oil',
    img: 'https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'lemongrass-oil',
    name: 'Natural Lemongrass Oil',
    botanicalName: 'Cymbopogon citratus',
    category: 'Essential Oils',
    chemicalMarker: 'Citral',
    standardization: 'Citral ≥ 75%',
    uses: ['Flavouring', 'Antimicrobial', 'Insect repellent'],
    benefits: ['Antimicrobial', 'Insect repellent', 'Stress relief', 'Flavouring'],
    applications: ['Insect repellents', 'Aromatherapy', 'Food flavouring', 'Cleaning products'],
    shortDescription: 'High-citral lemongrass essential oil — widely used as a natural insect repellent, flavouring agent, and antimicrobial in personal care, household, and food & beverage applications.',
    moq: '5 kg',
    slug: 'natural-lemongrass-oil',
    img: 'https://images.pexels.com/photos/1407305/pexels-photo-1407305.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },

  // ─── PHARMACEUTICAL EXCIPIENTS (Waxoils) ────────────────────────────────────
  {
    id: 'beeswax',
    name: 'White / Yellow Beeswax IP/BP/Ph.Eur',
    category: 'Pharmaceutical Excipients',
    chemicalMarker: 'Esters of C24–C36 fatty acids',
    standardization: 'IP / BP / Ph.Eur monograph compliant',
    uses: ['Tablet coating', 'Ointment base', 'Emulsification'],
    benefits: ['Natural emollient', 'Controlled release matrix', 'Moisture barrier', 'Texture enhancer'],
    applications: ['Tablet coatings', 'Ointments & creams', 'Lip care', 'Suppository bases'],
    shortDescription: 'Pharmaceutical-grade natural beeswax meeting IP/BP/Ph.Eur monographs — used as an emollient, coating agent, sustained-release matrix, and consistency modifier in pharmaceutical and cosmetic formulations.',
    moq: '50 kg',
    slug: 'beeswax-pharmaceutical',
    img: 'https://images.pexels.com/photos/1537217/pexels-photo-1537217.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'carnauba-wax',
    name: 'Carnauba Wax IP/BP/Ph.Eur/NF',
    category: 'Pharmaceutical Excipients',
    chemicalMarker: 'Wax esters, Fatty alcohols',
    standardization: 'IP / BP / Ph.Eur / NF monograph compliant',
    uses: ['Tablet coating', 'Polishing agent', 'Sustained release'],
    benefits: ['High melting point coating', 'Tablet shine & protection', 'Moisture barrier', 'Sustained release'],
    applications: ['Film-coated tablets', 'Sugar-coated tablets', 'Cosmetic polishes', 'Confectionery glazing'],
    shortDescription: 'The hardest natural wax meeting all major pharmacopoeia standards — the preferred tablet polishing and coating agent providing gloss, moisture protection, and sustained-release matrix capability.',
    moq: '50 kg',
    slug: 'carnauba-wax',
    img: 'https://images.pexels.com/photos/1537217/pexels-photo-1537217.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'microcrystalline-wax',
    name: 'Microcrystalline Wax IP/NF',
    category: 'Pharmaceutical Excipients',
    chemicalMarker: 'Isoparaffins, Naphthenes',
    standardization: 'IP / NF monograph compliant',
    uses: ['Sustained release', 'Ointment base', 'Tablet coating'],
    benefits: ['Sustained-release matrix', 'Plasticity modifier', 'Moisture barrier', 'Consistency enhancer'],
    applications: ['Sustained-release tablets', 'Topical ointments', 'Suppositories', 'Cosmetic formulas'],
    shortDescription: 'Highly refined petroleum-derived wax with fine crystal structure meeting IP/NF standards — used as a sustained-release matrix, ointment base modifier, and plasticity agent in pharmaceutical manufacturing.',
    moq: '50 kg',
    slug: 'microcrystalline-wax',
    img: 'https://images.pexels.com/photos/1537217/pexels-photo-1537217.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'glyceryl-monostearate',
    name: 'Glyceryl Mono Stearate IP/Ph.Eur/USP',
    category: 'Pharmaceutical Excipients',
    chemicalMarker: 'Glyceryl monostearate',
    standardization: 'IP / Ph.Eur / USPNF monograph; GMS 40–55% BP available',
    uses: ['Emulsifier', 'Lubricant', 'Sustained release'],
    benefits: ['Emulsification', 'Tablet lubrication', 'Cream consistency', 'Sustained release'],
    applications: ['Emulsion creams & ointments', 'Tablet lubricant', 'Suppository bases', 'Food emulsification'],
    shortDescription: 'Versatile pharmaceutical emulsifier and lubricant in multiple compendial grades — GMS is one of the most widely used excipients in tablet manufacturing, topical formulations, and food processing.',
    moq: '50 kg',
    slug: 'glyceryl-monostearate',
    img: 'https://images.pexels.com/photos/1537217/pexels-photo-1537217.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },

  // ─── PHARMA APIs (INDION) ───────────────────────────────────────────────────
  {
    id: 'indion-294',
    name: 'INDION 294 — Tablet Disintegrant',
    category: 'Pharmaceutical APIs',
    chemicalMarker: 'Polacrillin Potassium USP/NF',
    standardization: 'USP / NF monograph compliant',
    uses: ['Super disintegrant', 'Tablet formulation'],
    benefits: ['300% moisture expansion', 'Faster tablet disintegration', 'Improved bioavailability', 'Compressible'],
    applications: ['Oral solid dosage forms', 'Immediate-release tablets', 'Chewable tablets'],
    shortDescription: 'Polacrillin Potassium USP/NF — expands on contact with moisture up to 300%, dramatically improving tablet disintegration time and drug bioavailability for oral solid dosage formulations.',
    moq: '10 kg',
    slug: 'indion-294-disintegrant',
    img: 'https://images.pexels.com/photos/139398/thermometer-headache-pain-pills-139398.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'indion-414',
    name: 'INDION 414 — Super Disintegrant',
    category: 'Pharmaceutical APIs',
    chemicalMarker: 'Super Disintegrant Resin',
    standardization: 'Proprietary specification',
    uses: ['ODT tablets', 'Dispersible tablets', 'Mouth-dissolving tablets'],
    benefits: ['1000% moisture expansion', 'Rapid mouth dissolving', 'Enhanced patient compliance', 'No bitter taste'],
    applications: ['ODT tablets', 'Mouth-dissolving strips', 'Dispersible tablets', 'Pediatric formulations'],
    shortDescription: 'Super disintegrant resin expanding 1000% on moisture contact — specifically designed for mouth-dissolving and dispersible tablet applications requiring ultra-fast disintegration and patient convenience.',
    moq: '10 kg',
    slug: 'indion-414-super-disintegrant',
    img: 'https://images.pexels.com/photos/139398/thermometer-headache-pain-pills-139398.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'indion-204',
    name: 'INDION 204 — Taste Masking Resin',
    category: 'Pharmaceutical APIs',
    chemicalMarker: 'Ion-Exchange Resin',
    standardization: 'Proprietary specification',
    uses: ['Taste masking', 'Bitter drug masking', 'Controlled release'],
    benefits: ['Effective bitter taste masking', 'Suitable for antibiotics', 'Patient-friendly formulations', 'Stable'],
    applications: ['Paediatric oral liquid formulations', 'Antibiotic syrups', 'Chewable tablets', 'Dispersible tablets'],
    shortDescription: 'Ion-exchange resin for taste masking of Ofloxacin, Norfloxacin, Roxithromycin, Cefpodoxime Proxetil, and Vitamin B-12 — enabling patient-friendly paediatric and adult oral formulations.',
    moq: '10 kg',
    slug: 'indion-204-taste-masking',
    img: 'https://images.pexels.com/photos/139398/thermometer-headache-pain-pills-139398.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
  {
    id: 'cholestyramine',
    name: 'Cholestyramine Resin USP (INDION 454)',
    category: 'Pharmaceutical APIs',
    chemicalMarker: 'Cholestyramine Resin',
    standardization: 'USP monograph compliant',
    uses: ['Cholesterol reduction', 'Bile acid sequestrant'],
    benefits: ['LDL cholesterol reduction', 'Bile acid binding', 'Hypercholesterolaemia treatment'],
    applications: ['Hypercholesterolaemia treatment', 'Cardiovascular drugs', 'Bile acid malabsorption'],
    shortDescription: 'Cholestyramine Resin USP (INDION 454) — bile acid sequestrant resin for reducing LDL cholesterol levels, approved for hypercholesterolaemia treatment. Available in pharmacopoeia-compliant powder form.',
    moq: '10 kg',
    slug: 'cholestyramine-resin-usp',
    img: 'https://images.pexels.com/photos/139398/thermometer-headache-pain-pills-139398.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
  },
];

/** Get unique categories from the catalog */
export function getCatalogCategories(): CatalogCategory[] {
  const cats = new Set(CATALOG_PRODUCTS.map((p) => p.category));
  return Array.from(cats) as CatalogCategory[];
}

/** Filter catalog by category and/or search term */
export function filterCatalog(
  products: CatalogProduct[],
  category?: string,
  search?: string,
): CatalogProduct[] {
  return products.filter((p) => {
    const matchCat = !category || category === 'All' || p.category === category;
    const q = (search ?? '').toLowerCase();
    const matchSearch =
      !q ||
      p.name.toLowerCase().includes(q) ||
      (p.botanicalName ?? '').toLowerCase().includes(q) ||
      p.shortDescription.toLowerCase().includes(q) ||
      (p.chemicalMarker ?? '').toLowerCase().includes(q) ||
      p.uses.some((u) => u.toLowerCase().includes(q)) ||
      p.benefits.some((b) => b.toLowerCase().includes(q));
    return matchCat && matchSearch;
  });
}
